EnrollmentApplication/EnrollmentApplication/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EnrollmentApplication.Models
{
    public class Enrollment
    {

        [Display(Name = "Enrollment Id")] 

        public virtual int EnrollmentID {get; set;}

        [Display(Name = "Student Id")]
        public virtual int StudentId { get; set; }


        [Display(Name = "Course Id")]
        public virtual int CourseId { get; set; }
        [Display(Name = "Grade")]
        [Required ]
        [RegularExpression("^[A-F]{1}$", ErrorMessage = "Enter value A , B, C, D, E, F")]
        public virtual string Grade { get; set; }
        public virtual Student Student { get; set; }
        public virtual Course Course { get; set; }

        public virtual  bool IsActive { get; set; }

        [Required]
        [Display(Name = "Assigned Campus")]

        public virtual string AssignedCampus { get; set; }


    [Required]
        [Display(Name = "Enrolled in Semester")]
        public virtual string EnrollmentSemester { get; set; }


        [Required]
        [Range(2018, int.MaxValue, ErrorMessage ="Enter value greater than 2018" )]

        public virtual int EnrollmentYear { get; set; }

        //InvalidChars
        [Display(Name = "Notes")]
        [Required]
        [InvalidChars("@", ErrorMessage ="Notes contains invalid characters!")]
        public virtual string Notes { get; set; }



    }
}

EnrollmentApplication/EnrollmentApplication/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnrollmentApplication.Data;
using EnrollmentApplication.Models;

namespace EnrollmentApplication.Controllers
{
    public class EnrollmentController : Controller
    {
        private EnrollmentDB db = new EnrollmentDB();


        public ActionResult StudentSearch(string q)
        {
            var student = GetStudent(q);
            return PartialView("_StudentSearch", student);
        }
        private List<Student> GetStudent(string searchString)

        {
            return db.Student
                .Where(a => a.StudentLastname.Contains(searchString))
                .ToList();
        }


        public ActionResult CourseSearch(string q)
        {
            var course = GetCourse(q);
            return PartialView("_CourseSearch",course);
        }

        private List<Course> GetCourse (string searchString) 
                {
            return db.Courses
     .Where(a => a.Title.Contains(searchString))
     .ToList();

        }




        // GET: Enrollment
        public ActionResult Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student);
            return View(enrollments.ToList());
        }

        // GET: Enrollment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollment/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title");
            ViewBag.StudentId = new SelectList(db.Student, "StudentID", "StudentLastname");
            return View();
        }

        // POST: Enrollment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnrollmentID,StudentId,FirstName,LastName,IsActive,AssignedCampus,EnrollmentSemester,EnrollmentYearCourseId,Grade,Notes")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Student, "StudentID", "StudentLastname", "StudentFirstName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Student, "StudentID", "StudentLastname","StudentFirstName", enrollment.StudentId);
            return View(enrollment);
        }

        // POST: Enrollment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EnrollmentID,StudentId,FirstName,LastName,CourseId,Grade, IsActive, AssignedCampus,EnrollmentSemester,EnrollmentYear,Notes")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Student, "StudentID", "StudentLastname", "StudentFirstName",enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnrollmentApplication/EnrollmentApplication/Views/Enrollment/Create.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Enrollment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentYear, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EnrollmentYear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EnrollmentYear, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AssignedCampus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AssignedCampus, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AssignedCampus, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentSemester, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.RadioButtonFor(model => model.EnrollmentSemester, "Spring", new { htmlAttributes = new { @class = "form-control" } })
            @Html.Label("Spring")
            @Html.RadioButtonFor(model => model.EnrollmentSemester, "Summer", new { htmlAttributes = new { @class = "form-control" } })
            @Html.Label("Summer")
            @Html.RadioButtonFor(model => model.EnrollmentSemester, "Fall", new { htmlAttributes = new { @class = "form-control" } })
            @Html.Label("Fall")
            @Html.ValidationMessageFor(model => model.EnrollmentSemester, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnrollmentApplication/EnrollmentApplication/Views/Enrollment/Delete.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.StudentLastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.StudentLastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EnrollmentApplication/EnrollmentApplication/Views/Enrollment/Details.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.StudentLastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.StudentLastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentSemester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnrollmentSemester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AssignedCampus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AssignedCampus)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentYear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnrollmentYear)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnrollmentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EnrollmentApplication/EnrollmentApplication/Views/Enrollment/Edit.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Enrollment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EnrollmentID)

    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentYear, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EnrollmentYear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EnrollmentYear, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AssignedCampus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AssignedCampus, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AssignedCampus, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentSemester, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.RadioButtonFor(model => model.EnrollmentSemester, "Spring", new { htmlAttributes = new { @class = "form-control" } })
            @Html.Label("Spring")
            @Html.RadioButtonFor(model => model.EnrollmentSemester, "Summer", new { htmlAttributes = new { @class = "form-control" } })
            @Html.Label("Summer")
            @Html.RadioButtonFor(model => model.EnrollmentSemester, "Fall", new { htmlAttributes = new { @class = "form-control" } })
            @Html.Label("Fall")
            @Html.ValidationMessageFor(model => model.EnrollmentSemester, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnrollmentApplication/EnrollmentApplication/Views/Enrollment/Index.cshtml
@model IEnumerable<EnrollmentApplication.Models.Enrollment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>











@using (Ajax.BeginForm("StudentSearch", "Enrollment", new AjaxOptions

{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "GET",
    OnFailure = "searchFailed",
    LoadingElementId = "ajax-loader",
    UpdateTargetId = "searchresults"
}))

{
    <input type="text" name="q" />
    <input type="submit" value="Student search" />
    <img id="ajax-loader"
         src="@Url.Content("~/Content/ajax-loader.gif" ) "
         style="display:none" />

   








}






@using (Ajax.BeginForm("CourseSearch", "Enrollment", new AjaxOptions

{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "GET",
    OnFailure = "searchFailed",
    LoadingElementId = "ajax-loader",
    UpdateTargetId = "searchresults"
}))

{
    <input type="text" name="q" />
    <input type="submit" value="Course search" />
    <img id="ajax-loader"
         src="@Url.Content("~/Content/ajax-loader.gif" ) "
         style="display:none" />



}






<div id="searchresults"></div>









<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.StudentLastname)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.StudentLastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.EnrollmentID }) |
                @Html.ActionLink("Details", "Details", new { id = item.EnrollmentID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EnrollmentID })
            </td>
        </tr>
    }

</table>

@section Scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script src="~/Scripts/Apps/StudentScripts.js"></script>

    <script src="~/Scripts/Apps/CourseScripts.js"></script>
}

EnrollmentApplication/EnrollmentApplication/Views/Enrollment/_CourseSearch.cshtml
@model IEnumerable<EnrollmentApplication.Models.Course>





<div id=" searchresults">
    <ul>


        @foreach (var item in Model)
        {
            <li>@item.Title</li>
            <li>@item.CourseDescription</li>
        }
    </ul>
</div>

EnrollmentApplication/EnrollmentApplication/Views/Enrollment/_StudentSearch.cshtml
@model IEnumerable<EnrollmentApplication.Models.Student>





<div id=" searchresults" >
<ul>
    

    @foreach(var item in Model)
    {
        <li>@item.StudentFirstName</li>
        <li> @item.StudentLastname</li>
    }
</ul>
</div>